<?php
// includes/lang.php

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$active_lang = $_SESSION['preferred_lang'] ?? 'en';

$translations = [
    'en' => [
        'Dashboard' => 'Dashboard',
        'My Workspace' => 'My Workspace',
        'Dedicated Workspaces' => 'Dedicated Workspaces',
        'Virtual Meetings' => 'Virtual Meetings',
        'User Manual' => 'User Manual',
        'Company Hub' => 'Company Hub',
        'Company Intranet' => 'Company Intranet',
        'Pulse Surveys' => 'Pulse Surveys',
        'CRM & Sales' => 'CRM & Sales',
        'Lead Management' => 'Lead Management',
        'Vendor Network' => 'Vendor Network',
        'Project & Task Management' => 'Project & Task Management',
        'Project Portfolio' => 'Project Portfolio',
        'Task Matrix' => 'Task Matrix',
        'Agile Kanban' => 'Agile Kanban',
        'Gantt Charts' => 'Gantt Charts',
        'Time & Expense Tracking' => 'Time & Expense Tracking',
        'Timesheets' => 'Timesheets',
        'Financial Operations' => 'Financial Operations',
        'Invoice Management' => 'Invoice Management',
        'Procurement' => 'Procurement',
        'Expense Tracking' => 'Expense Tracking',
        'Human Capital' => 'Human Capital',
        'HR Dashboard' => 'HR Dashboard',
        'Attendance & Time' => 'Attendance & Time',
        'Leave Management' => 'Leave Management',
        'Payroll & Compensation' => 'Payroll & Compensation',
        'Recruitment (ATS)' => 'Recruitment (ATS)',
        'Onboarding Portal' => 'Onboarding Portal',
        'Organizational Chart' => 'Organizational Chart',
        'Performance Reviews' => 'Performance Reviews',
        'Asset & Facility' => 'Asset & Facility',
        'Asset Inventory' => 'Asset Inventory',
        'Knowledge Base' => 'Knowledge Base',
        'Support & Analytics' => 'Support & Analytics',
        'Helpdesk / Ticketing' => 'Helpdesk / Ticketing',
        'Training & L&D' => 'Training & L&D',
        'KPI Dashboards' => 'KPI Dashboards',
        'Form Builder' => 'Form Builder',
        'Form Analytics' => 'Form Analytics',
        'Feedback / Survey' => 'Feedback / Survey',
        'Workspace Utilities' => 'Workspace Utilities',
        'Document Repository' => 'Document Repository',
        'Office Suite' => 'Office Suite',
        'Shared Calendar' => 'Shared Calendar',
        'Room Booking' => 'Room Booking',
        'System & Reports' => 'System & Reports',
        'Report Generator' => 'Report Generator',
        'Audit Trail' => 'Audit Trail',
        'System Settings' => 'System Settings',
        'User Directory' => 'User Directory',
        'Toggle Theme' => 'Toggle Theme',
        'Profile' => 'Profile',
        'Logout' => 'Logout',
        'Search anything...' => 'Search anything...',
        'Notifications' => 'Notifications',
        'Mark all read' => 'Mark all read'
    ],
    'hi' => [
        'Dashboard' => 'डैशबोर्ड',
        'My Workspace' => 'मेरा कार्यक्षेत्र',
        'Dedicated Workspaces' => 'समर्पित कार्यक्षेत्र',
        'Virtual Meetings' => 'वर्चुअल मीटिंग्स',
        'User Manual' => 'उपयोगकर्ता नियमावली',
        'Company Hub' => 'कंपनी हब',
        'Company Intranet' => 'कंपनी इंट्रानेट',
        'Pulse Surveys' => 'पल्स सर्वेक्षण',
        'CRM & Sales' => 'सीआरएम और बिक्री',
        'Lead Management' => 'लीड प्रबंधन',
        'Vendor Network' => 'विक्रेता नेटवर्क',
        'Project & Task Management' => 'परियोजना और कार्य प्रबंधन',
        'Project Portfolio' => 'परियोजना पोर्टफोलियो',
        'Task Matrix' => 'कार्य मैट्रिक्स',
        'Agile Kanban' => 'एजाइल कानबान',
        'Gantt Charts' => 'गैंट चार्ट',
        'Time & Expense Tracking' => 'समय और व्यय ट्रैकिंग',
        'Timesheets' => 'टाइमशीट',
        'Financial Operations' => 'वित्तीय संचालन',
        'Invoice Management' => 'चालान प्रबंधन',
        'Procurement' => 'खरीद (प्रोक्योरमेंट)',
        'Expense Tracking' => 'व्यय ट्रैकिंग',
        'Human Capital' => 'मानव पूंजी',
        'HR Dashboard' => 'एचआर डैशबोर्ड',
        'Attendance & Time' => 'उपस्थिति और समय',
        'Leave Management' => 'अवकाश प्रबंधन',
        'Payroll & Compensation' => 'पेरोल और मुआवजा',
        'Recruitment (ATS)' => 'भर्ती (एटीएस)',
        'Onboarding Portal' => 'ऑनबोर्डिंग पोर्टल',
        'Organizational Chart' => 'संगठनात्मक चार्ट',
        'Performance Reviews' => 'प्रदर्शन समीक्षा',
        'Asset & Facility' => 'संपत्ति और सुविधा',
        'Asset Inventory' => 'संपत्ति सूची',
        'Knowledge Base' => 'ज्ञानकोष',
        'Support & Analytics' => 'समर्थन और एनालिटिक्स',
        'Helpdesk / Ticketing' => 'हेल्पडेस्क / टिकटिंग',
        'Training & L&D' => 'प्रशिक्षण और एल एंड डी',
        'KPI Dashboards' => 'केपीआई डैशबोर्ड',
        'Form Builder' => 'फॉर्म बिल्डर',
        'Form Analytics' => 'फॉर्म एनालिटिक्स',
        'Feedback / Survey' => 'प्रतिक्रिया / सर्वेक्षण',
        'Workspace Utilities' => 'कार्यक्षेत्र उपयोगिताएँ',
        'Document Repository' => 'दस्तावेज़ भंडार',
        'Office Suite' => 'ऑफिस सुइट',
        'Shared Calendar' => 'साझा कैलेंडर',
        'Room Booking' => 'कमरा बुकिंग',
        'System & Reports' => 'सिस्टम और रिपोर्ट',
        'Report Generator' => 'रिपोर्ट जनरेटर',
        'Audit Trail' => 'ऑडिट ट्रेल',
        'System Settings' => 'सिस्टम सेटिंग्स',
        'User Directory' => 'उपयोगकर्ता निर्देशिका',
        'Toggle Theme' => 'थीम बदलें',
        'Profile' => 'प्रोफ़ाइल',
        'Logout' => 'लॉग आउट',
        'Search anything...' => 'कुछ भी खोजें...',
        'Notifications' => 'सूचनाएं',
        'Mark all read' => 'सभी को पढ़ा हुआ चिह्नित करें'
    ]
];

function __($text) {
    global $translations, $active_lang;
    return $translations[$active_lang][$text] ?? $text;
}
